# Configurações AWS - Agora lendo variáveis de ambiente
aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION:us-east-2}

# Exemplo de configuração de banco ou tabela (se necessário)
dynamodb.table.name=${TABLE_NAME:LucroLivre}