spring.application.name=lucrolivre-api

jdbc:postgresql://host.docker.internal:5432/seu_banco
spring.datasource.username=admin
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
server.address=0.0.0.0
spring.lifecycle.timeout-per-shutdown-phase=30s